# Using Built-In Functions (Using Pytorch)

In [1]:
import torch
import numpy as np
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [85, 100, 60],
                   [95, 80, 55],
                   [105, 120, 75],
                   [78, 90, 50],
                   [82, 70, 45]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [98, 110],
                    [88, 95],
                    [115, 140],
                    [76, 85],
                    [65, 75]], dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

[tensor([[102.,  43.,  37.],
         [ 82.,  70.,  45.],
         [ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 87., 134.,  58.]]),
 tensor([[ 22.,  37.],
         [ 65.,  75.],
         [ 81., 101.],
         [103., 119.],
         [119., 133.]])]

In [2]:
tensor_ds = TensorDataset(inputs, targets)
tensor_dl = DataLoader(tensor_ds, batch_size=5, shuffle=True)

next(iter(tensor_dl))

[tensor([[102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 82.,  70.,  45.],
         [ 78.,  90.,  50.],
         [ 87., 134.,  58.]]),
 tensor([[ 22.,  37.],
         [103., 119.],
         [ 65.,  75.],
         [ 76.,  85.],
         [119., 133.]])]

In [3]:
tensor_ds

In [4]:
#Replacing Model with built-in function
class SimpleNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear1 = nn.Linear(3, 4)
    self.act1 = nn.ReLU()
    self.linear2 = nn.Linear(4, 2)

  def forward(self, x):
    x = self.linear1(x)
    x = self.act1(x)
    x = self.linear2(x)
    return x

model = SimpleNN()
# for name, params in model.named_parameters():
#   print("Name:", name)
#   print("Param", params)


#Replacing MSE with built-in function
# mse = torch.nn.MSELoss()
mae = torch.nn.L1Loss()

#Optimizer
opt = torch.optim.Adam(model.parameters(), lr = 0.00001)

# Training step
def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    preds = model(inputs)
    loss = loss_fn(preds, targets)

    loss.backward()
    if epoch%100 == 99:
      print(loss.item())

    opt.step()
    opt.zero_grad()


opt_SGD = torch.optim.SGD(model.parameters(), lr = 0.00001)

# Training step
def fit_SGD(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb, yb in tensor_dl:
      preds = model(xb)
      loss = loss_fn(preds, yb)

      loss.backward()
      opt.step()
      opt.zero_grad()
    if epoch%100 == 99:
      print(loss.item())



# fit(1000, model, mae, opt)
fit_SGD(1000, model, mae, opt_SGD)
preds = model(inputs)
print(preds)

99.60823059082031
107.70174407958984
78.2110595703125
88.166259765625
92.93743133544922
99.16616821289062
93.36399841308594
72.94586944580078
104.86198425292969
107.98197937011719
tensor([[ 0.2081,  0.0700],
        [ 0.2081,  0.0700],
        [-0.9773,  0.0471],
        [-0.9330, -0.2344],
        [ 0.2081,  0.0700],
        [ 0.2081,  0.0700],
        [ 0.2081,  0.0700],
        [ 0.2081,  0.0700],
        [ 0.2081,  0.0700],
        [ 0.2081,  0.0700]], grad_fn=<AddmmBackward0>)
